# Check `docs/pipeline.md` to get info about this file
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

  - name: kite
    type: docker-image
    source:
      repository: heliostech/kite
      tag: v0.2.2

resources:
  - name: k8s
    type: kite
    source:
      certificate-authority: ((barong_k8s_cert))
      token: ((barong_k8s_token))
      endpoint: https://35.187.119.28

  - name: barong-repository
    type: git
    source:
      uri: git@github.com:rubykube/barong.git
      branch: master
      private_key: ((barong_git_private_key))

  - name: pull-requests
    type: pull-request
    source:
      access_token: ((barong_github_token))
      base: master
      private_key: ((barong_git_private_key))
      repo: rubykube/barong
      uri: git@github.com:rubykube/barong.git

  - name: barong-image
    type: docker-image
    source:
      repository: gcr.io/helios-public/barong
      username: _json_key
      password: ((barong_gcr_password))

  - name: slack-alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/((barong_slack_webhook))

jobs:
  - name: pr-build
    plan:
      - get: pull-requests
        trigger: true
      - task: tag
        file: pull-requests/config/pipelines/tasks/create-pull-requests-tag.yml
      - put: barong-image
        params:
          build: pull-requests
          tag: tag/name

  - name: pr-unit
    serial: true
    plan:
      - get: pull-requests
        passed: [pr-build]
        trigger: true
      - get: barong-image
        passed: [pr-build]
        trigger: true
      - put: pull-requests
        params:
          path: pull-requests
          status: pending
      - task: run-tests
        image: barong-image
        file: pull-requests/config/pipelines/tasks/run-unit.yml
        on_success:
          do:
          - put: pull-requests
            params:
              path: pull-requests
              status: success
          - put: slack-alert
            params:
              channel: '#ci-alerts'
              text: |
                barong PR tests have passed! :thumbsup_all:
                Check it out at:
                $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                or at:
                $ATC_EXTERNAL_URL/builds/$BUILD_ID
                see on github:
                `cat pull-requests/.git/url`
        on_failure:
          do:
          - put: pull-requests
            params:
              path: pull-requests
              status: failure
          - put: slack-alert
            params:
              channel: '#ci-alerts'
              text: |
                barong PR tests have failed! :thumbsdown_all:
                Check it out at:
                $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                or at:
                $ATC_EXTERNAL_URL/builds/$BUILD_ID
                see on github:
                `cat pull-requests/.git/url`

  - name: master-build
    serial: true
    plan:
      - get: barong-repository
        trigger: true
      - task: tag
        file: barong-repository/config/pipelines/tasks/create-repository-tag.yml
      - put: barong-image
        params:
          build: barong-repository
          tag: tag/name
        on_success:
          try:
            put: slack-alert
            params:
              channel: '#ci-alerts'
              text: |
                barong master branch was built and pushed!
                Check it out at:
                $ATC_EXTERNAL_URL/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                or at:
                $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: master-unit
    serial: true
    plan:
      - get: barong-repository
        passed: [master-build]
        trigger: true
      - get: barong-image
        passed: [master-build]
        trigger: true
      - task: run-tests
        image: barong-image
        file: barong-repository/config/pipelines/tasks/run-unit.yml
        on_success:
          try:
            put: slack-alert
            params:
              channel: '#ci-alerts'
              text: |
                barong master tests have passed! :thumbsup_all:
                Check it out at:
                $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                or at:
                $ATC_EXTERNAL_URL/builds/$BUILD_ID

        on_failure:
          put: slack-alert
          params:
            channel: '#ci-alerts'
            text: |
              barong master tests have failed! :thumbsdown_all:
              Check it out at:
              $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: master-deploy
    serial: true
    plan:
      - get: barong-repository
        passed: [master-unit]
        trigger: true
      - put: k8s
        params:
          command: "bash -xc 'cd /tmp/build/put/barong-repository && VERSION=$(git rev-parse --short=8 HEAD) make deploy'"
        on_success:
          try:
            put: slack-alert
            params:
              channel: '#ci-alerts'
              text: |
                barong deployment has succeeded! :thumbsup_all:
                Check it out at:
                $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
                or at:
                $ATC_EXTERNAL_URL/builds/$BUILD_ID
