---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: heliostech/kite
run:
  path: sh
  args: ['-xc', 'cd barong-repository && git rev-parse --short=8 HEAD > ../tag/name']
inputs:
  - name: barong-repository
outputs:
  - name: tag
